application: explorers-army
version: 0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /user(.*)
  script: user.app

libraries:
- name: webapp2
  version: "2.5.1"
